#!/usr/bin/env bash

# This file is part of midnight-node.
# Copyright (C) Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Spins up a fresh postgres preloaded with a snapshot generated by
# build-snapshot.sh, then runs the midnight node and watches its logs until
# block $SYNC_UNTIL (default 1000) is imported.
#
# The postgres container generates a self-signed TLS cert at first boot, since
# midnight-node enforces TLS for its db-sync connection (PgSslMode::Require).

set -Eeuo pipefail

NODE_IMAGE=${NODE_IMAGE:-ghcr.io/midnight-ntwrk/midnight-node:latest}
POSTGRES_IMAGE=${POSTGRES_IMAGE:-postgres:17.4-alpine}
SNAPSHOT=${SNAPSHOT:-snapshot.sql}
CFG_PRESET=${CFG_PRESET:-mainnet}
SYNC_UNTIL=${SYNC_UNTIL:-1000}
NETWORK_NAME=${NETWORK_NAME:-midnight-sync-test}
PG_CONTAINER=${PG_CONTAINER:-midnight-sync-test-pg}
NODE_CONTAINER=${NODE_CONTAINER:-midnight-sync-test-node}
PG_PASSWORD=${PG_PASSWORD:-cardano}
SYNC_TIMEOUT_SECS=${SYNC_TIMEOUT_SECS:-1800}
STALL_TIMEOUT_SECS=${STALL_TIMEOUT_SECS:-180}
PRINT_LOGS=${PRINT_LOGS:-0}

if [[ ! -f "$SNAPSHOT" ]]; then
  echo "Snapshot file not found: $SNAPSHOT" >&2
  echo "Run scripts/sync-test/build-snapshot.sh first." >&2
  exit 1
fi

KEEP_CONTAINERS=${KEEP_CONTAINERS:-0}
cleanup() {
  local rc=$?
  if [[ "$KEEP_CONTAINERS" != "1" ]]; then
    echo "Cleaning up..." >&2
    docker logs "$NODE_CONTAINER" >/tmp/midnight-node.log 2>&1 || true
    docker logs "$PG_CONTAINER" >/tmp/midnight-pg.log 2>&1 || true
    if [[ "$PRINT_LOGS" == "1" ]]; then
      echo "==> midnight-node logs:" >&2
      cat /tmp/midnight-node.log >&2 || true
      echo "==> postgres logs:" >&2
      cat /tmp/midnight-pg.log >&2 || true
    fi
    docker rm -f "$NODE_CONTAINER" "$PG_CONTAINER" >/dev/null 2>&1 || true
    docker network rm "$NETWORK_NAME" >/dev/null 2>&1 || true
  else
    echo "KEEP_CONTAINERS=1: leaving containers running for inspection" >&2
  fi
  exit $rc
}
trap cleanup EXIT

docker rm -f "$NODE_CONTAINER" "$PG_CONTAINER" >/dev/null 2>&1 || true
docker network rm "$NETWORK_NAME" >/dev/null 2>&1 || true
docker network create "$NETWORK_NAME" >/dev/null

PG_INIT='set -e
SSL_DIR=/etc/ssl/postgres
mkdir -p "$SSL_DIR"
apk add --no-cache openssl >/dev/null
openssl req -new -x509 -days 365 -nodes \
  -out "$SSL_DIR/server.crt" -keyout "$SSL_DIR/server.key" \
  -subj "/CN=postgres" \
  -addext "subjectAltName=DNS:postgres,DNS:'"$PG_CONTAINER"',IP:127.0.0.1" 2>/dev/null
chown postgres:postgres "$SSL_DIR/server.crt" "$SSL_DIR/server.key"
chmod 600 "$SSL_DIR/server.key"
chmod 644 "$SSL_DIR/server.crt"
exec docker-entrypoint.sh postgres \
  -c ssl=on \
  -c ssl_cert_file=$SSL_DIR/server.crt \
  -c ssl_key_file=$SSL_DIR/server.key'

echo "==> Starting postgres ($POSTGRES_IMAGE)..." >&2
# --shm-size: postgres uses POSIX shared memory (/dev/shm) for parallel-query
# scratch space. The docker default is 64 MB, which is small enough that even
# moderate parallel scans (the cnight observation queries trigger several)
# fail with "No space left on device" inside dsm_impl_posix.
docker run -d --rm \
  --name "$PG_CONTAINER" \
  --network "$NETWORK_NAME" \
  --network-alias postgres \
  --shm-size=1g \
  -e POSTGRES_PASSWORD="$PG_PASSWORD" \
  -e POSTGRES_USER=cardano \
  -e POSTGRES_DB=cexplorer \
  --entrypoint sh \
  "$POSTGRES_IMAGE" \
  -c "$PG_INIT" >/dev/null

echo "==> Waiting for postgres..." >&2
for _ in $(seq 1 60); do
  if docker exec "$PG_CONTAINER" pg_isready -U cardano -d cexplorer >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Loading snapshot ($(stat -c %s "$SNAPSHOT" | awk '{printf "%.1f MB", $1/1048576}'))..." >&2
case "$SNAPSHOT" in
  *.xz)  CAT="xz -dc" ;;
  *.gz)  CAT="gzip -dc" ;;
  *)     CAT="cat" ;;
esac
$CAT "$SNAPSHOT" | docker exec -i "$PG_CONTAINER" psql -U cardano -d cexplorer -v ON_ERROR_STOP=1 -q

PG_DSN="postgres://cardano:${PG_PASSWORD}@${PG_CONTAINER}:5432/cexplorer"

echo "==> Starting midnight-node ($NODE_IMAGE) with CFG_PRESET=$CFG_PRESET..." >&2
NODE_KEY=$(head -c 32 /dev/urandom | hexdump -v -e '/1 "%02x"')

# No --rm: keep the container so we can inspect logs after it exits. The node
# key is passed via --node-key rather than a bind-mounted file so we don't
# depend on a host path being visible to the docker daemon (which fails inside
# sandboxed shells where /tmp is a private tmpfs).
docker run -d \
  --name "$NODE_CONTAINER" \
  --network "$NETWORK_NAME" \
  -e CFG_PRESET="$CFG_PRESET" \
  -e DB_SYNC_POSTGRES_CONNECTION_STRING="$PG_DSN" \
  -e CARDANO_SECURITY_PARAMETER=2160 \
  -e CARDANO_ACTIVE_SLOTS_COEFF=0.05 \
  -e BLOCK_STABILITY_MARGIN=10 \
  -e SHOW_CONFIG=true \
  "$NODE_IMAGE" \
  --node-key "$NODE_KEY" \
  --no-mdns --no-telemetry --no-prometheus \
  ${EXTRA_NODE_ARGS:-} >/dev/null

echo "==> Watching node logs for sync to block $SYNC_UNTIL (timeout ${SYNC_TIMEOUT_SECS}s)..." >&2
deadline=$(( $(date +%s) + SYNC_TIMEOUT_SECS ))
last_progress=$(date +%s)
last_block=0

while true; do
  now=$(date +%s)
  if (( now > deadline )); then
    echo "FAIL: deadline exceeded (${SYNC_TIMEOUT_SECS}s); reached block $last_block" >&2
    docker logs --tail 80 "$NODE_CONTAINER" >&2 || true
    exit 1
  fi
  if ! docker ps --format '{{.Names}}' | grep -q "^${NODE_CONTAINER}$"; then
    echo "FAIL: node container exited; reached block $last_block" >&2
    docker logs --tail 80 "$NODE_CONTAINER" >&2 || true
    exit 1
  fi

  current=$(docker logs --tail 200 "$NODE_CONTAINER" 2>&1 \
    | grep -oE 'best:[[:space:]]*#[0-9]+' \
    | tail -1 | grep -oE '[0-9]+' || true)
  current=${current:-0}

  if (( current > last_block )); then
    last_block=$current
    last_progress=$now
    echo "  best: #$last_block" >&2
  fi

  if (( last_block >= SYNC_UNTIL )); then
    echo "OK: node reached block $last_block (target: $SYNC_UNTIL)" >&2
    exit 0
  fi

  if (( now - last_progress > STALL_TIMEOUT_SECS )); then
    echo "FAIL: no sync progress for ${STALL_TIMEOUT_SECS}s; stuck at block $last_block" >&2
    docker logs --tail 120 "$NODE_CONTAINER" >&2 || true
    exit 1
  fi

  sleep 5
done
