// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import fs from "fs";
import path from "path";
import YAML from "yaml";

export const MOCKED_CONFIG_DIRNAME = "mocked-config";
const MOCK_BRIDGE_DATA_DIR = "res/mock-bridge-data";

/** Deterministic path of the override yaml generated by generateMockComposeOverride. */
export function mockOverridePath(composeDir: string, network: string): string {
  return path.join(path.resolve(composeDir), `${network}.mock.override.yaml`);
}

export interface MockOverrideOptions {
  /** Compose directory; mocked-config/, res/mock-bridge-data/, and the override yaml all live here. */
  composeDir: string;
  /** Network name (devnet, qanet, ...) — drives override + mock-registrations filename. */
  network: string;
  /** Validator service names. Index matches mock-authorities seeds layout (validatorServices[i] -> seeds/validator-i). */
  validatorServices: string[];
  /** Non-validator services that still need fork-mode env (e.g. qanet's boot-node). */
  extraServices?: string[];
}

/**
 * Generates the docker-compose override that turns the per-network base compose
 * into a fork-mode bring-up: validators read seeds from mock-authorities output,
 * the main-chain follower runs in mock mode, and DB sync is disabled.
 *
 * Returns the absolute path to the written override yaml. Also copies
 * mocked-config/mock-registrations.json into res/mock-bridge-data/<net>-mock.json
 * so the compose volume mount resolves.
 */
export function generateMockComposeOverride(opts: MockOverrideOptions): string {
  const { composeDir, network, validatorServices, extraServices = [] } = opts;
  const composeAbs = path.resolve(composeDir);
  const mockFileName = `${network}-mock.json`;
  const containerMountPath = `/${MOCK_BRIDGE_DATA_DIR}/${mockFileName}`;
  const hostRelPath = `./${MOCK_BRIDGE_DATA_DIR}/${mockFileName}`;

  const srcRegistrations = path.join(
    composeAbs,
    MOCKED_CONFIG_DIRNAME,
    "mock-registrations.json",
  );
  if (!fs.existsSync(srcRegistrations)) {
    throw new Error(
      `Expected mock-registrations.json at ${srcRegistrations}; run mock-authorities convert first.`,
    );
  }
  const destBridgeDir = path.join(composeAbs, MOCK_BRIDGE_DATA_DIR);
  fs.mkdirSync(destBridgeDir, { recursive: true });
  fs.copyFileSync(srcRegistrations, path.join(destBridgeDir, mockFileName));

  const services: Record<string, unknown> = {};

  validatorServices.forEach((svc, i) => {
    services[svc] = {
      environment: {
        USE_MAIN_CHAIN_FOLLOWER_MOCK: "true",
        MOCK_REGISTRATIONS_FILE: containerMountPath,
        AURA_SEED_FILE: "/seeds/aura.seed",
        GRANDPA_SEED_FILE: "/seeds/grandpa.seed",
        CROSS_CHAIN_SEED_FILE: "/seeds/cross_chain.seed",
        // Blank these out so the base compose's SEED_PHRASE / DB_SYNC envs
        // don't sneak through; fork-mode reads keys from seed files and
        // disables Cardano db-sync entirely.
        SEED_PHRASE: "",
        DB_SYNC_POSTGRES_CONNECTION_STRING: "",
      },
      volumes: [
        `./${MOCKED_CONFIG_DIRNAME}/seeds/validator-${i}:/seeds`,
        // Overlay just the mock json into the image's baked-in /res so we
        // keep chain-spec and the other res files intact.
        `${hostRelPath}:${containerMountPath}:ro`,
      ],
    };
  });

  for (const svc of extraServices) {
    services[svc] = {
      environment: {
        USE_MAIN_CHAIN_FOLLOWER_MOCK: "true",
        MOCK_REGISTRATIONS_FILE: containerMountPath,
        DB_SYNC_POSTGRES_CONNECTION_STRING: "",
      },
      volumes: [`${hostRelPath}:${containerMountPath}:ro`],
    };
  }

  const overridePath = path.join(composeAbs, `${network}.mock.override.yaml`);
  fs.writeFileSync(overridePath, YAML.stringify({ services }));
  return overridePath;
}
