// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_federated_authority_observation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `Intel(R) Xeon(R) Platinum 8488C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./midnight-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// *
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./runtime/src/weights/
// --header
// ./LICENSE_HEADER.txt
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_federated_authority_observation`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_federated_authority_observation::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `FederatedAuthorityObservation::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilMembership::Members` (r:1 w:1)
	/// Proof: `CouncilMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `Council::Proposals` (r:1 w:0)
	/// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CouncilMembership::Prime` (r:1 w:0)
	/// Proof: `CouncilMembership::Prime` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::CouncilMainchainMembers` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::CouncilMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommitteeMembership::Members` (r:1 w:0)
	/// Proof: `TechnicalCommitteeMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (r:1 w:0)
	/// Proof: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Council::Members` (r:0 w:1)
	/// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Council::Prime` (r:0 w:1)
	/// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 9]`.
	/// The range of component `b` is `[1, 9]`.
	fn reset_members_only_council(a: u32, b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `706 + a * (92 ±0) + b * (60 ±0)`
		//  Estimated: `3529 + a * (98 ±0) + b * (58 ±0)`
		// Minimum execution time: 55_107_000 picoseconds.
		Weight::from_parts(58_122_607, 0)
			.saturating_add(Weight::from_parts(0, 3529))
			// Standard Error: 4_968
			.saturating_add(Weight::from_parts(354_962, 0).saturating_mul(a.into()))
			// Standard Error: 4_968
			.saturating_add(Weight::from_parts(162_695, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(Weight::from_parts(0, 98).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 58).saturating_mul(b.into()))
	}
	/// Storage: `FederatedAuthorityObservation::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilMembership::Members` (r:1 w:0)
	/// Proof: `CouncilMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::CouncilMainchainMembers` (r:1 w:0)
	/// Proof: `FederatedAuthorityObservation::CouncilMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommitteeMembership::Members` (r:1 w:1)
	/// Proof: `TechnicalCommitteeMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `TechnicalCommittee::Proposals` (r:1 w:0)
	/// Proof: `TechnicalCommittee::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TechnicalCommitteeMembership::Prime` (r:1 w:0)
	/// Proof: `TechnicalCommitteeMembership::Prime` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommittee::Members` (r:0 w:1)
	/// Proof: `TechnicalCommittee::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommittee::Prime` (r:0 w:1)
	/// Proof: `TechnicalCommittee::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 9]`.
	/// The range of component `b` is `[1, 9]`.
	fn reset_members_only_technical_committee(a: u32, b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590 + a * (60 ±0) + b * (93 ±0)`
		//  Estimated: `3529 + a * (63 ±0) + b * (93 ±0)`
		// Minimum execution time: 53_733_000 picoseconds.
		Weight::from_parts(55_495_054, 0)
			.saturating_add(Weight::from_parts(0, 3529))
			// Standard Error: 4_890
			.saturating_add(Weight::from_parts(239_875, 0).saturating_mul(a.into()))
			// Standard Error: 4_890
			.saturating_add(Weight::from_parts(272_665, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(Weight::from_parts(0, 63).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 93).saturating_mul(b.into()))
	}
	/// Storage: `FederatedAuthorityObservation::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilMembership::Members` (r:1 w:1)
	/// Proof: `CouncilMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `Council::Proposals` (r:1 w:0)
	/// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `CouncilMembership::Prime` (r:1 w:0)
	/// Proof: `CouncilMembership::Prime` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::CouncilMainchainMembers` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::CouncilMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommitteeMembership::Members` (r:1 w:1)
	/// Proof: `TechnicalCommitteeMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `TechnicalCommittee::Proposals` (r:1 w:0)
	/// Proof: `TechnicalCommittee::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommitteeMembership::Prime` (r:1 w:0)
	/// Proof: `TechnicalCommitteeMembership::Prime` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Council::Members` (r:0 w:1)
	/// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Council::Prime` (r:0 w:1)
	/// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommittee::Members` (r:0 w:1)
	/// Proof: `TechnicalCommittee::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommittee::Prime` (r:0 w:1)
	/// Proof: `TechnicalCommittee::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 9]`.
	/// The range of component `b` is `[1, 9]`.
	fn reset_members(a: u32, b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `896 + a * (92 ±0) + b * (93 ±0)`
		//  Estimated: `6068 + a * (100 ±0) + b * (90 ±0)`
		// Minimum execution time: 84_457_000 picoseconds.
		Weight::from_parts(88_742_867, 0)
			.saturating_add(Weight::from_parts(0, 6068))
			// Standard Error: 7_216
			.saturating_add(Weight::from_parts(289_425, 0).saturating_mul(a.into()))
			// Standard Error: 7_216
			.saturating_add(Weight::from_parts(222_223, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(11))
			.saturating_add(Weight::from_parts(0, 100).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 90).saturating_mul(b.into()))
	}
	/// Storage: `FederatedAuthorityObservation::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `FederatedAuthorityObservation::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CouncilMembership::Members` (r:1 w:0)
	/// Proof: `CouncilMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::CouncilMainchainMembers` (r:1 w:0)
	/// Proof: `FederatedAuthorityObservation::CouncilMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TechnicalCommitteeMembership::Members` (r:1 w:0)
	/// Proof: `TechnicalCommitteeMembership::Members` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (r:1 w:0)
	/// Proof: `FederatedAuthorityObservation::TechnicalCommitteeMainchainMembers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 10]`.
	/// The range of component `b` is `[1, 10]`.
	fn reset_members_none(a: u32, b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `400 + a * (60 ±0) + b * (60 ±0)`
		//  Estimated: `1880 + a * (60 ±0) + b * (60 ±0)`
		// Minimum execution time: 27_501_000 picoseconds.
		Weight::from_parts(28_218_802, 0)
			.saturating_add(Weight::from_parts(0, 1880))
			// Standard Error: 1_662
			.saturating_add(Weight::from_parts(165_763, 0).saturating_mul(a.into()))
			// Standard Error: 1_662
			.saturating_add(Weight::from_parts(152_538, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 60).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 60).saturating_mul(b.into()))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_520_000 picoseconds.
		Weight::from_parts(4_229_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_543_000 picoseconds.
		Weight::from_parts(4_159_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_265_000 picoseconds.
		Weight::from_parts(3_901_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_276_000 picoseconds.
		Weight::from_parts(3_873_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
