// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_partner_chains_bridge`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ws1`, CPU: `AMD Ryzen 9 9950X 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/midnight-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_partner_chains_bridge
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./runtime/src/weights/
// --header
// ./LICENSE_HEADER.txt
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_partner_chains_bridge`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_partner_chains_bridge::WeightInfo for WeightInfo<T> {
	/// Storage: `Bridge::InherentExecutedThisBlock` (r:1 w:1)
	/// Proof: `Bridge::InherentExecutedThisBlock` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Midnight::StateKey` (r:1 w:1)
	/// Proof: `Midnight::StateKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `C2MBridge::ApprovedMcTxHashes` (r:256 w:256)
	/// Proof: `C2MBridge::ApprovedMcTxHashes` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `C2MBridge::TransferCounter` (r:1 w:1)
	/// Proof: `C2MBridge::TransferCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Midnight::ParentTimestamp` (r:1 w:0)
	/// Proof: `Midnight::ParentTimestamp` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Bridge::DataCheckpoint` (r:0 w:1)
	/// Proof: `Bridge::DataCheckpoint` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 256]`.
	fn handle_transfers(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266 + t * (53 ±0)`
		//  Estimated: `1753 + t * (2523 ±0)`
		// Minimum execution time: 119_931_000 picoseconds.
		Weight::from_parts(121_251_000, 0)
			.saturating_add(Weight::from_parts(0, 1753))
			// Standard Error: 895_713
			.saturating_add(Weight::from_parts(199_150_767, 0).saturating_mul(t.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_parts(0, 2523).saturating_mul(t.into()))
	}
	/// Storage: `Bridge::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `Bridge::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: Some(305), added: 800, mode: `MaxEncodedLen`)
	/// Storage: `Bridge::DataCheckpoint` (r:0 w:1)
	/// Proof: `Bridge::DataCheckpoint` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_610_000 picoseconds.
		Weight::from_parts(1_880_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
