// This file is part of midnight-node.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_session_validator_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `Intel(R) Xeon(R) Platinum 8488C`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./midnight-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_session_validator_management
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./runtime/src/weights/
// --header
// ./LICENSE_HEADER.txt
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_session_validator_management`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_session_validator_management::WeightInfo for WeightInfo<T> {
	/// Storage: `SessionCommitteeManagement::CurrentCommittee` (r:1 w:0)
	/// Proof: `SessionCommitteeManagement::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// Storage: `SessionCommitteeManagement::NextCommittee` (r:1 w:1)
	/// Proof: `SessionCommitteeManagement::NextCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[0, 10000]`.
	fn set(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `1301495`
		// Minimum execution time: 12_516_000 picoseconds.
		Weight::from_parts(13_415_000, 0)
			.saturating_add(Weight::from_parts(0, 1301495))
			// Standard Error: 160
			.saturating_add(Weight::from_parts(122_462, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SessionCommitteeManagement::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `SessionCommitteeManagement::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: Some(178), added: 673, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_405_000 picoseconds.
		Weight::from_parts(4_017_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
