use crate::cli_parsers::{self as cli};
use clap::Args;
use serde::Deserialize;
use std::path::{Path, PathBuf};

use crate::genesis_generator::{
	FundingArgs, GENESIS_NONCE_SEED, GenesisGenerator, IcsConfig, ReserveConfig,
};
use midnight_node_ledger_helpers::{
	LedgerParameters, Serializable, SystemTransaction, Tagged, WalletSeed,
	midnight_serialize::tagged_deserialize, serialize,
};

#[derive(Deserialize)]
pub struct CNightGeneratesDustConfig {
	#[serde(with = "hex")]
	system_tx: Vec<u8>,
}

#[derive(Debug, Clone, Args)]
pub struct GenerateGenesisArgs {
	/// Seed for genesis block generation
	#[arg(
        short,
        long,
        value_parser = cli::hex_str_decode::<[u8; 32]>,
        default_value = GENESIS_NONCE_SEED,
    )]
	nonce_seed: [u8; 32],
	// Target Network
	#[arg(long)]
	network: String,
	// Proof Server Host
	#[arg(long, short)]
	proof_server: Option<String>,
	/// File containing the wallet seeds to fund. Optional - if not provided, no faucet wallets
	/// will be funded (appropriate for mainnet).
	#[arg(long)]
	seeds_file: Option<PathBuf>,
	/// File containing cNight generates Dust config. The system_tx in this file is
	/// applied to the LedgerState.
	#[arg(long)]
	cnight_generates_dust_config: PathBuf,
	/// File containing ICS (Illiquid Circulation Supply) configuration for initializing the
	/// treasury. Generated by `midnight-node generate-ics-genesis` command.
	#[arg(long)]
	ics_config: PathBuf,
	/// File containing reserve contract configuration. Generated by
	/// `midnight-node generate-reserve-genesis` command.
	#[arg(long)]
	reserve_config: Option<PathBuf>,
	/// File containing ledger parameters config (JSON).
	#[arg(long)]
	ledger_parameters_config: PathBuf,
	/// Arguments for funding wallets
	#[command(flatten)]
	funding: FundingArgs,
	/// Output directory
	#[arg(long, short = 'o', default_value = "out")]
	out_dir: String,
}

pub async fn execute(
	args: GenerateGenesisArgs,
) -> Result<GenesisGenerator, Box<dyn std::error::Error + Send + Sync>> {
	let dir = Path::new(&args.out_dir);
	std::fs::create_dir_all(&dir)?;

	println!("generating genesis for network {}...", &args.network);

	// Parse the seeds file (if provided)
	let seeds: Option<Vec<WalletSeed>> = if let Some(seeds_file) = args.seeds_file {
		let seeds_str = std::fs::read_to_string(&seeds_file)?;
		let seeds_json: serde_json::Value = serde_json::from_str(&seeds_str)?;
		let parsed_seeds: Result<Vec<WalletSeed>, Box<dyn std::error::Error + Send + Sync>> =
			seeds_json
				.as_object()
				.unwrap()
				.iter()
				.map(|(_k, v)| {
					let wallet_seed_str =
						v.as_str().ok_or("seeds file object value was not a string")?;
					let wallet_seed = WalletSeed::try_from_hex_str(wallet_seed_str)?;
					Ok(wallet_seed)
				})
				.collect();
		println!("Funding {} faucet wallets", parsed_seeds.as_ref().map(|s| s.len()).unwrap_or(0));
		Some(parsed_seeds?)
	} else {
		println!("No seeds file provided - skipping faucet wallet funding");
		None
	};

	// Parse the cNight generates dust config file
	let cnight_system_tx: Option<SystemTransaction> = {
		let json_str = std::fs::read_to_string(&args.cnight_generates_dust_config)?;
		let config: CNightGeneratesDustConfig = serde_json::from_str(&json_str)?;
		Some(tagged_deserialize(&mut &config.system_tx[..])?)
	};

	// Parse and validate the ICS config
	let ics_config: Option<IcsConfig> = {
		let json_str = std::fs::read_to_string(&args.ics_config)
			.map_err(|e| format!("Failed to read ICS config {:?}: {}", args.ics_config, e))?;
		let config: IcsConfig = serde_json::from_str(&json_str)
			.map_err(|e| format!("Failed to parse ICS config: {}", e))?;
		config.validate().map_err(|e| format!("ICS config validation failed: {}", e))?;
		println!(
			"ICS config loaded: {} Night from {} UTxOs",
			config.total_amount,
			config.utxos.len()
		);
		Some(config)
	};

	// Parse and validate the reserve config (if provided)
	let reserve_config: Option<ReserveConfig> = if let Some(ref path) = args.reserve_config {
		let json_str = std::fs::read_to_string(path)
			.map_err(|e| format!("Failed to read reserve config {:?}: {}", path, e))?;
		let config: ReserveConfig = serde_json::from_str(&json_str)
			.map_err(|e| format!("Failed to parse reserve config: {}", e))?;
		config
			.validate()
			.map_err(|e| format!("Reserve config validation failed: {}", e))?;
		println!(
			"Reserve config loaded: {} Night from {} UTxOs",
			config.total_amount,
			config.utxos.len()
		);
		Some(config)
	} else {
		None
	};

	// Parse the ledger parameters config file
	let ledger_parameters: Option<LedgerParameters> = {
		let json_str = std::fs::read_to_string(&args.ledger_parameters_config)?;
		let params: LedgerParameters = serde_json::from_str(&json_str)?;
		println!("Using ledger parameters from {}", args.ledger_parameters_config.display());
		Some(params)
	};

	let genesis = GenesisGenerator::new(
		args.nonce_seed,
		&args.network,
		args.proof_server,
		args.funding,
		seeds.as_deref(),
		cnight_system_tx,
		ics_config,
		reserve_config,
		ledger_parameters,
	)
	.await?;

	let state_filename = format!("genesis_state_{}.mn", &args.network);
	let block_filename = format!("genesis_block_{}.mn", &args.network);
	let genesis_state_path = dir.join(&state_filename);
	let genesis_tx_path = dir.join(&block_filename);

	serialize_and_write(&genesis.state, &genesis_state_path)?;

	let json_bytes = serde_json::to_vec(&genesis.txs)?;
	std::fs::write(&genesis_tx_path, json_bytes)?;
	println!("Written to {}", genesis_tx_path.display());

	println!("Number of genesis txs: {}", genesis.txs.batches[0].len());

	Ok(genesis)
}

fn serialize_and_write<T: Serializable + Tagged>(
	value: &T,
	file_path: &PathBuf,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
	let serialized_value = serialize(value)?;
	std::fs::write(file_path, serialized_value)?;

	println!("Written to {}", file_path.display());

	Ok(())
}

#[cfg(test)]
mod test {
	use super::serialize_and_write;
	use crate::cli::{Cli, run_command};
	use crate::{DefaultDB, LedgerState};
	use clap::Parser;
	use midnight_node_ledger_helpers::INITIAL_PARAMETERS;
	use std::{
		env::temp_dir,
		fs::{self, remove_file},
	};

	#[test]
	fn test_serialize_and_write() {
		let state = LedgerState::<DefaultDB>::new("undeployed");

		let path = temp_dir().join("state.mn");

		assert!(serialize_and_write(&state, &path).is_ok());
		assert!(path.exists());
		remove_file(&path).expect("It should be removed");
	}

	fn check_file(path: &str) {
		let file_exist = fs::exists(path).expect("file exist failed");
		assert!(file_exist);
		remove_file(path).expect("file failed to remove");
	}

	#[tokio::test]
	async fn test_generate_genesis() {
		let path = temp_dir().join("undeployed-seeds.json");
		let mut seed_map = std::collections::HashMap::new();
		seed_map.insert(
			"wallet-seed-0",
			"0000000000000000000000000000000000000000000000000000000000000001",
		);

		let mut dest = std::fs::OpenOptions::new()
			.create(true)
			.write(true)
			.open(&path)
			.expect("failed to open seed file as writer");
		serde_json::to_writer(&mut dest, &seed_map).expect("failed to write seed file");

		let args = vec![
			"midnight-node-toolkit",
			"generate-genesis",
			"--network",
			"undeployed",
			"--seeds-file",
			path.to_str().unwrap(),
			"--cnight-generates-dust-config",
			"../../res/dev/cnight-config.json",
			"--ics-config",
			"../../res/dev/ics-config.json",
			"--ledger-parameters-config",
			"../../res/dev/ledger-parameters-config.json",
		];

		let cli = Cli::parse_from(args);
		run_command(cli.command).await.expect("should work");

		let path = "out/genesis_state_undeployed.mn";
		check_file(path);

		let path = "out/genesis_block_undeployed.mn";
		check_file(path);
	}

	#[test]
	fn print_default_ledger_parameters_json() {
		let json = serde_json::to_string_pretty(&INITIAL_PARAMETERS)
			.expect("failed to serialize INITIAL_PARAMETERS");
		println!("{}", json);
	}

	#[test]
	fn test_deserialize_ledger_parameters_config() {
		let json_str =
			std::fs::read_to_string("../../res/dev/ledger-parameters-config.json").unwrap();
		let _params: super::LedgerParameters = serde_json::from_str(&json_str)
			.expect("failed to deserialize ledger parameters config");
	}
}
