chain = "res/perfnet/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "Midnight Perfnet"
chainspec_id = "midnight_perfnet"
chainspec_genesis_state = "res/genesis/genesis_state_perfnet.mn"
chainspec_genesis_block = "res/genesis/genesis_block_perfnet.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/perfnet/pc-chain-config.json"
chainspec_cnight_genesis = "res/perfnet/cnight-config.json"
chainspec_ics_config = "res/perfnet/ics-config.json"
chainspec_reserve_config = "res/perfnet/reserve-config.json"
chainspec_federated_authority_config = "res/perfnet/federated-authority-config.json"
chainspec_system_parameters_config = "res/perfnet/system-parameters-config.json"
chainspec_permissioned_candidates_config = "res/perfnet/permissioned-candidates-config.json"
chainspec_registered_candidates_addresses = "res/perfnet/registered-candidates-addresses.json"
