chain = "res/preprod/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "Midnight Preprod"
chainspec_id = "midnight_preprod"
chainspec_genesis_state = "res/genesis/genesis_state_preprod.mn"
chainspec_genesis_block = "res/genesis/genesis_block_preprod.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/preprod/pc-chain-config.json"
chainspec_cnight_genesis = "res/preprod/cnight-config.json"
chainspec_ics_config = "res/preprod/ics-config.json"
chainspec_federated_authority_config = "res/preprod/federated-authority-config.json"
chainspec_system_parameters_config = "res/preprod/system-parameters-config.json"
chainspec_permissioned_candidates_config = "res/preprod/permissioned-candidates-config.json"
chainspec_registered_candidates_addresses = "res/preprod/registered-candidates-addresses.json"

cardano_security_parameter = 2160
cardano_active_slots_coeff = 0.05
block_stability_margin = 10

mc__first_epoch_timestamp_millis = 1655769600000
mc__first_epoch_number = 4
mc__epoch_duration_millis = 432000000
mc__first_slot_number = 86400
mc__slot_duration_millis = 1000
