chain = "res/stagenet/chain-spec-raw.json"
base_path = "node/chain"

chainspec_name = "Midnight Stagenet"
chainspec_id = "midnight_stagenet"
chainspec_genesis_state = "res/genesis/genesis_state_stagenet.mn"
chainspec_genesis_block = "res/genesis/genesis_block_stagenet.mn"
chainspec_chain_type = "live"
chainspec_pc_chain_config = "res/stagenet/pc-chain-config.json"
chainspec_cnight_genesis = "res/stagenet/cnight-config.json"
chainspec_ics_config = "res/stagenet/ics-config.json"
chainspec_reserve_config = "res/stagenet/reserve-config.json"
chainspec_federated_authority_config = "res/stagenet/federated-authority-config.json"
chainspec_system_parameters_config = "res/stagenet/system-parameters-config.json"
chainspec_permissioned_candidates_config = "res/stagenet/permissioned-candidates-config.json"
chainspec_registered_candidates_addresses = "res/stagenet/registered-candidates-addresses.json"
chainspec_c2m_bridge_config = "res/stagenet/c2m-bridge-config.json"
