name: Validate GitHub Actions Workflows

on:
  merge_group:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  push:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

jobs:
  actionlint:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2
        with:
          matcher: true # Enable GitHub annotations for errors
          fail-on-error: true # Fail CI when errors are found
