name: +partnerchains-dev (Build Docker image that contains Partner Chains tools)

on:
  workflow_dispatch:
  schedule:
    # Once a week
    - cron: "0 0 * * 0"
# no top level default permissions for security reasons
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  run:
    name: Build an image with Partner Chains tools
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: EarthBuild/actions-setup@cae2d9ab68894d8402751fe42e07c7cca0272f7f
        with:
          version: v0.8.16
          github-token: ${{ github.token }}
          use-cache: false

      - name: Checkout node repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          submodules: true

      - name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #v4.2.0

        with:
          registry: ghcr.io
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Run build
        run: |
          mkdir -p "$HOME"/.cargo
          echo "[net]" >> "$HOME"/.cargo/config
          echo "git-fetch-with-cli = true" >> "$HOME"/.cargo/config

          . ./.envrc && earthly --ci --push +partnerchains-dev
