name: Nightly Build Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# no top level default permissions for security reasons
permissions:
  contents: read

jobs:
  build_node:
    name: Build Node against latest
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      FORCE_COLOR: 1
    outputs:
      node_result: ${{ steps.run_earthly.outputs.node_result }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
        with:
          submodules: true

      - uses: EarthBuild/actions-setup@cae2d9ab68894d8402751fe42e07c7cca0272f7f
        with:
          version: v0.8.16
          github-token: ${{ github.token }}
          use-cache: false

      - name: Cat the Cargo.toml
        run: cat ./Cargo.toml

      - name: Free disk space
        run: scripts/free-disk-space.sh

      - name: Run check
        run: |
          mkdir -p "$HOME"/.cargo
          echo "[net]" >> "$HOME"/.cargo/config
          echo "git-fetch-with-cli = true" >> "$HOME"/.cargo/config

          . ./.envrc && earthly --platform=linux/amd64 +node-image
