name: Scan
permissions: {}

on:
  push:
    branches: [main]
    paths-ignore:
      - "changes/**"
  pull_request:
    branches: [main]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.event_name != 'merge_group' && format('{0}-{1}', github.workflow, github.head_ref) || github.run_id }}
  cancel-in-progress: true

env:
  # needed to stop rate limiting of compact download.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2

      - name: Scan code
        uses: midnightntwrk/upload-sarif-github-action@9856edc26a43e2d0cc3b391888bce2295377bdd7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
